#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 28 21:16:33 2020

@author: pim01001
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt 

#page = requests.get("https://www.sec.gov/ix?doc=/Archives/edgar/data/1318605/000156459020019931/tsla-10q_20200331.htm")
#print(page.status_code)

#Tesla = BeautifulSoup(page.content, 'html.parser')

#zz=Tesla.find_all(id='dynamic-xbrl-form')
#print(Tesla.prettify())


# reads in all the stocks and converts it to uppercase
stocks=pd.read_csv('/home/pim01001/Documents/Bootcamp/python/proj/yahoo/stock_info.csv')
stocks['Stocks']=stocks['Stocks'].str.upper()
# output dataframe
comb_df  = pd.DataFrame()


for z in stocks['Stocks']:
    page1 = requests.get('https://finance.yahoo.com/quote/'+ z +'/financials?p='+z)
    print(page1.status_code) 
    
    
    yahoo = BeautifulSoup(page1.content, 'html.parser')
    ll=yahoo.find(class_="D(tbr) C($primaryColor)")

    # this will get us the Top Row
    len(list(ll.find_all('span')))
    list(ll.find_all('span'))[0].get_text()

    data= yahoo.find(class_="D(tbrg)")
    
  
    # getting col names information
    head_col = yahoo.find(class_="D(tbhg)")
    col_names=head_col.get_text(separator=':').split(':')

    
    # this gives header information for the table
    col_names.append('Ticker') 
    total= pd.DataFrame(columns=col_names)
    #comb_df = pd.DataFrame(columns=col_names)
    
    # this gets data for the finacial table and for loop organizes it
    test = data.find_all(class_="D(tbr) fi-row Bgc($hoverBgColor):h")
    for i in range(len(test)):
        temp=test[i].get_text(separator=':').split(':')
        print(temp)
        total.loc[i]=[str(temp[0])] + temp[1:6] +[str(z)]
    
    def growth_percent(data_df):
        x,y=data_df.shape
        for b in range(1:3):
            print(((data_df.iloc[:,b+1]-data_df.iloc[:,b])/data_df.iloc[:,b])*100)
        
        
        print(data_df.shape)
    growth_percent(total.iloc[[0,4],])
    
    
    comb_df=comb_df.append(total.iloc[[0,4],])
    # this converts number in these rows to 
    
# gets rid of commas and turn into int    
comb_df[col_names[2:6]]=comb_df[col_names[2:6]].apply(lambda x: x.str.replace(',','')).astype('int32')

# need to compute average growth so take 2017-2016 / 2016  
# then average for  4 years

#comb_df.to_csv(r'/home/pim01001/Documents/Bootcamp/python/proj/yahoo/comb.csv', 
#               index = False, header=True)

#print(total.iloc[[0,4],])
    
    # get page

page1 = requests.get('https://finance.yahoo.com/quote/'+stocks[0]+'/financials?p='+stocks[0])
    


# plotting the data
# left = [1, 2, 3, 4, 5]
# plt.bar(range(len(total.iloc[1,1:6])),height=total.iloc[1,1:6], tick_label = total.columns[1:6], width = 0.8)
# plt.show()